packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@prisma/client'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - '@scarf/scarf'
  - prisma
  - sharp
  - unrs-resolver
